"""kb content tiers: kb_block_class + kb_rules_digest

Revision ID: 063ef74ba336
Revises: 4d1754afce23
Create Date: 2026-08-12 16:17:39.004616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


revision: str = '063ef74ba336'
down_revision: Union[str, None] = '4d1754afce23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kb_block_class',
    sa.Column('content_hash', sa.String(length=32), nullable=False),
    sa.Column('content_class', sa.String(length=16), nullable=False),
    sa.Column('origin', sa.String(length=16), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('content_hash')
    )
    op.create_table('kb_rules_digest',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('root_key', sa.String(length=36), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('char_count', sa.Integer(), nullable=False),
    sa.Column('compiled_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('root_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kb_rules_digest')
    op.drop_table('kb_block_class')
    # ### end Alembic commands ###
