"""request and dev_run repo binding

Revision ID: 2fab54c2cc96
Revises: 4d1754afce23
Create Date: 2026-08-12 16:29:17.398239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


revision: str = '2fab54c2cc96'
down_revision: Union[str, None] = '063ef74ba336'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dev_run', sa.Column('repo_id', sa.String(length=36), nullable=True))
    op.create_foreign_key('fk_dev_run_repo_id', 'dev_run', 'project_repo', ['repo_id'], ['id'], ondelete='SET NULL')
    op.add_column('request', sa.Column('repo_id', sa.String(length=36), nullable=True))
    op.create_foreign_key('fk_request_repo_id', 'request', 'project_repo', ['repo_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_request_repo_id', 'request', type_='foreignkey')
    op.drop_column('request', 'repo_id')
    op.drop_constraint('fk_dev_run_repo_id', 'dev_run', type_='foreignkey')
    op.drop_column('dev_run', 'repo_id')
    # ### end Alembic commands ###
