"""api token scope + hub credit grants

Revision ID: 3c48e382753c
Revises: 68dca0dccfe6
Create Date: 2026-07-10 02:58:23.352200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


revision: str = '3c48e382753c'
down_revision: Union[str, None] = '68dca0dccfe6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hub_credit_grant',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('detail', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hub_credit_grant_idempotency_key'), 'hub_credit_grant', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_hub_credit_grant_org_id'), 'hub_credit_grant', ['org_id'], unique=False)
    op.add_column('api_token', sa.Column('scope', sa.String(length=16), server_default='user', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_token', 'scope')
    op.drop_index(op.f('ix_hub_credit_grant_org_id'), table_name='hub_credit_grant')
    op.drop_index(op.f('ix_hub_credit_grant_idempotency_key'), table_name='hub_credit_grant')
    op.drop_table('hub_credit_grant')
    # ### end Alembic commands ###
