"""project_repo summarize_to_issue

Revision ID: 4d1754afce23
Revises: 959c4332745c
Create Date: 2026-08-10 23:42:55.701018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


revision: str = '4d1754afce23'
down_revision: Union[str, None] = '3c67fe58f700'  # re-chained onto this repo's head
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_repo', sa.Column('summarize_to_issue', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_repo', 'summarize_to_issue')
    # ### end Alembic commands ###
