"""kb procedure registry

Revision ID: 639181b7e604
Revises: 063ef74ba336
Create Date: 2026-08-12 16:48:19.207109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


revision: str = '639181b7e604'
down_revision: Union[str, None] = '2fab54c2cc96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kb_procedure',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('root_key', sa.String(length=36), nullable=False),
    sa.Column('rel', sa.String(length=512), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=32), nullable=False),
    sa.Column('compiled_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kb_procedure_content_hash'), 'kb_procedure', ['content_hash'], unique=False)
    op.create_index(op.f('ix_kb_procedure_root_key'), 'kb_procedure', ['root_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kb_procedure_root_key'), table_name='kb_procedure')
    op.drop_index(op.f('ix_kb_procedure_content_hash'), table_name='kb_procedure')
    op.drop_table('kb_procedure')
    # ### end Alembic commands ###
