"""project dev_harness pin

Revision ID: 685d59ada66e
Revises: c9f4a1b7d203
Create Date: 2026-08-29 19:15:28.097383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


revision: str = '685d59ada66e'
down_revision: Union[str, None] = 'c9f4a1b7d203'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('dev_harness', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'dev_harness')
    # ### end Alembic commands ###
