"""programs

Revision ID: 68dca0dccfe6
Revises: fc6148a7149d
Create Date: 2026-07-09 22:21:03.006273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


revision: str = '68dca0dccfe6'
down_revision: Union[str, None] = 'fc6148a7149d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('program',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('short_description', sa.String(length=512), nullable=False),
    sa.Column('readme_md', sa.Text(), nullable=False),
    sa.Column('gitlab_repo_path', sa.String(length=255), nullable=False),
    sa.Column('gitlab_project_id', sa.Integer(), nullable=True),
    sa.Column('gitlab_web_url', sa.String(length=512), nullable=True),
    sa.Column('default_branch', sa.String(length=128), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('schedulable', sa.Boolean(), nullable=False),
    sa.Column('openai_base_url', sa.String(length=512), nullable=True),
    sa.Column('openai_api_key_enc', sa.Text(), nullable=True),
    sa.Column('model_name', sa.String(length=128), nullable=True),
    sa.Column('credit_markup', sa.Float(), nullable=True),
    sa.Column('timeout_minutes', sa.Integer(), nullable=False),
    sa.Column('cpu_request', sa.String(length=16), nullable=False),
    sa.Column('cpu_limit', sa.String(length=16), nullable=False),
    sa.Column('mem_request', sa.String(length=16), nullable=False),
    sa.Column('mem_limit', sa.String(length=16), nullable=False),
    sa.Column('input_template', sa.JSON(), nullable=True),
    sa.Column('last_check_state', sa.String(length=16), nullable=True),
    sa.Column('last_check_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_check_run_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gitlab_repo_path')
    )
    op.create_index(op.f('ix_program_title'), 'program', ['title'], unique=False)
    op.create_table('program_instance',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('program_id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('inputs_enc', sa.Text(), nullable=True),
    sa.Column('webhook_url', sa.String(length=512), nullable=False),
    sa.Column('schedule_enabled', sa.Boolean(), nullable=False),
    sa.Column('schedule_cron', sa.String(length=64), nullable=False),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ssh_public_key', sa.Text(), nullable=False),
    sa.Column('ssh_private_key_enc', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['program.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_program_instance_next_run_at'), 'program_instance', ['next_run_at'], unique=False)
    op.create_index(op.f('ix_program_instance_org_id'), 'program_instance', ['org_id'], unique=False)
    op.create_index(op.f('ix_program_instance_program_id'), 'program_instance', ['program_id'], unique=False)
    op.create_table('program_run',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('program_id', sa.String(length=36), nullable=False),
    sa.Column('instance_id', sa.String(length=36), nullable=True),
    sa.Column('org_id', sa.String(length=36), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('exit_code', sa.String(length=16), nullable=True),
    sa.Column('error', sa.String(length=512), nullable=True),
    sa.Column('log_tail', sa.Text(), nullable=True),
    sa.Column('output_text', sa.Text(), nullable=True),
    sa.Column('output_files', sa.JSON(), nullable=True),
    sa.Column('tokens_input', sa.Integer(), nullable=False),
    sa.Column('tokens_output', sa.Integer(), nullable=False),
    sa.Column('cost_credits', sa.Float(), nullable=False),
    sa.Column('webhook_status', sa.String(length=16), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['instance_id'], ['program_instance.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['program.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_program_run_created_at'), 'program_run', ['created_at'], unique=False)
    op.create_index(op.f('ix_program_run_instance_id'), 'program_run', ['instance_id'], unique=False)
    op.create_index(op.f('ix_program_run_program_id'), 'program_run', ['program_id'], unique=False)
    op.create_index(op.f('ix_program_run_state'), 'program_run', ['state'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_program_run_state'), table_name='program_run')
    op.drop_index(op.f('ix_program_run_program_id'), table_name='program_run')
    op.drop_index(op.f('ix_program_run_instance_id'), table_name='program_run')
    op.drop_index(op.f('ix_program_run_created_at'), table_name='program_run')
    op.drop_table('program_run')
    op.drop_index(op.f('ix_program_instance_program_id'), table_name='program_instance')
    op.drop_index(op.f('ix_program_instance_org_id'), table_name='program_instance')
    op.drop_index(op.f('ix_program_instance_next_run_at'), table_name='program_instance')
    op.drop_table('program_instance')
    op.drop_index(op.f('ix_program_title'), table_name='program')
    op.drop_table('program')
    # ### end Alembic commands ###
