"""issue watch event history

Revision ID: 6d303ab57290
Revises: 3df4fc7b25fa
Create Date: 2026-08-05 22:18:22.410055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


revision: str = '6d303ab57290'
down_revision: Union[str, None] = '3df4fc7b25fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issue_watch_event',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('issue_url', sa.String(length=512), nullable=True),
    sa.Column('issue_title', sa.String(length=255), nullable=True),
    sa.Column('request_id', sa.String(length=36), nullable=True),
    sa.Column('detail', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['request.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_issue_watch_event_created_at'), 'issue_watch_event', ['created_at'], unique=False)
    op.create_index(op.f('ix_issue_watch_event_project_id'), 'issue_watch_event', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_issue_watch_event_project_id'), table_name='issue_watch_event')
    op.drop_index(op.f('ix_issue_watch_event_created_at'), table_name='issue_watch_event')
    op.drop_table('issue_watch_event')
    # ### end Alembic commands ###
