"""quote canceled status and refunded_credits

Revision ID: 6dffa25cdbf7
Revises: d4e5f6a7b8c9
Create Date: 2026-07-06 14:45:37.002093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


revision: str = '6dffa25cdbf7'
down_revision: Union[str, None] = 'd4e5f6a7b8c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quote', sa.Column('refunded_credits', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quote', 'refunded_credits')
    # ### end Alembic commands ###
