"""devrun ledger and parallel limit

Revision ID: 7dd77ff9a94c
Revises: b7e2c4a91f05
Create Date: 2026-08-07 13:10:29.991607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


revision: str = '7dd77ff9a94c'
down_revision: Union[str, None] = 'b7e2c4a91f05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dev_run',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=True),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('workspace_dir', sa.String(length=255), nullable=False),
    sa.Column('branch', sa.String(length=80), nullable=True),
    sa.Column('pr_number', sa.Integer(), nullable=True),
    sa.Column('pr_url', sa.String(length=512), nullable=True),
    sa.Column('run_log', sa.Text(), nullable=True),
    sa.Column('run_error', sa.String(length=512), nullable=True),
    sa.Column('harness_version', sa.String(length=32), nullable=True),
    sa.Column('security_review', sa.JSON(), nullable=True),
    sa.Column('acceptance', sa.JSON(), nullable=True),
    sa.Column('tokens_consumed', sa.Integer(), nullable=False),
    sa.Column('cost_credits', sa.Float(), nullable=False),
    sa.Column('billed_through', sa.Integer(), nullable=False),
    sa.Column('predecessor_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['predecessor_id'], ['dev_run.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['request.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dev_run_created_at'), 'dev_run', ['created_at'], unique=False)
    op.create_index(op.f('ix_dev_run_project_id'), 'dev_run', ['project_id'], unique=False)
    op.create_index(op.f('ix_dev_run_state'), 'dev_run', ['state'], unique=False)
    op.create_index('uq_devrun_active_request', 'dev_run', ['request_id'], unique=True, postgresql_where=sa.text("state IN ('queued', 'running', 'awaiting_merge', 'deploying')"))
    op.add_column('project', sa.Column('dev_parallel_limit', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'dev_parallel_limit')
    op.drop_index('uq_devrun_active_request', table_name='dev_run', postgresql_where=sa.text("state IN ('queued', 'running', 'awaiting_merge', 'deploying')"))
    op.drop_index(op.f('ix_dev_run_state'), table_name='dev_run')
    op.drop_index(op.f('ix_dev_run_project_id'), table_name='dev_run')
    op.drop_index(op.f('ix_dev_run_created_at'), table_name='dev_run')
    op.drop_table('dev_run')
    # ### end Alembic commands ###
