"""quote details, credit pricing, decision, attachments

Revision ID: 84b2d70a85e7
Revises: b2d3e4f5a6b7
Create Date: 2026-07-06 06:15:45.262383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


revision: str = '84b2d70a85e7'
down_revision: Union[str, None] = 'b2d3e4f5a6b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quote_attachment',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('quote_id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['quote_id'], ['quote.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quote_attachment_quote_id'), 'quote_attachment', ['quote_id'], unique=False)
    # server_default: the table may already hold Stripe-path quotes
    op.add_column('quote', sa.Column('title', sa.String(length=255), nullable=False,
                                     server_default=''))
    op.add_column('quote', sa.Column('details', sa.Text(), nullable=False,
                                     server_default=''))
    op.add_column('quote', sa.Column('price_credits', sa.Float(), nullable=True))
    op.add_column('quote', sa.Column('decision_comment', sa.Text(), nullable=True))
    op.add_column('quote', sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quote', 'decided_at')
    op.drop_column('quote', 'decision_comment')
    op.drop_column('quote', 'price_credits')
    op.drop_column('quote', 'details')
    op.drop_column('quote', 'title')
    op.drop_index(op.f('ix_quote_attachment_quote_id'), table_name='quote_attachment')
    op.drop_table('quote_attachment')
    # ### end Alembic commands ###
