"""request delivery snapshot

Revision ID: 8555f099ca48
Revises: 564487232548
Create Date: 2026-09-03 05:03:01.391697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


revision: str = '8555f099ca48'
down_revision: Union[str, None] = '564487232548'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('delivery', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request', 'delivery')
    # ### end Alembic commands ###
