"""project routines

Revision ID: 929b25b5dc58
Revises: 677c1728c6f2
Create Date: 2026-08-14 01:32:30.859958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '929b25b5dc58'
down_revision: Union[str, None] = '677c1728c6f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_routine',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('schedule_cron', sa.String(length=64), nullable=False),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_request_id', sa.String(length=36), nullable=True),
    sa.Column('repo_id', sa.String(length=36), nullable=True),
    sa.Column('last_skip_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['last_request_id'], ['request.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['repo_id'], ['project_repo.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_routine_next_run_at'), 'project_routine', ['next_run_at'], unique=False)
    op.create_index(op.f('ix_project_routine_project_id'), 'project_routine', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_routine_project_id'), table_name='project_routine')
    op.drop_index(op.f('ix_project_routine_next_run_at'), table_name='project_routine')
    op.drop_table('project_routine')
    # ### end Alembic commands ###
