"""user full_name + org address fields

Revision ID: 93b8413aea41
Revises: 3906c156dc89
Create Date: 2026-07-08 01:14:07.992800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


revision: str = '93b8413aea41'
down_revision: Union[str, None] = '3906c156dc89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization', sa.Column('address_line1', sa.String(length=255), nullable=True))
    op.add_column('organization', sa.Column('address_line2', sa.String(length=255), nullable=True))
    op.add_column('organization', sa.Column('postal_code', sa.String(length=32), nullable=True))
    op.add_column('organization', sa.Column('city', sa.String(length=128), nullable=True))
    op.add_column('organization', sa.Column('country', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('full_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'full_name')
    op.drop_column('organization', 'country')
    op.drop_column('organization', 'city')
    op.drop_column('organization', 'postal_code')
    op.drop_column('organization', 'address_line2')
    op.drop_column('organization', 'address_line1')
    # ### end Alembic commands ###
