"""add_project_kind

Revision ID: 9736f8b68826
Revises: fd1e59138c16
Create Date: 2026-07-05 06:39:49.437199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


revision: str = '9736f8b68826'
down_revision: Union[str, None] = 'fd1e59138c16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('kind', sa.String(length=16), nullable=False,
                                       server_default='ai'))
    op.alter_column('project', 'speciality',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project', 'speciality',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.drop_column('project', 'kind')
    # ### end Alembic commands ###
