"""project_repo squash_on_merge

Revision ID: 9f1c8376a757
Revises: dc11add77d38
Create Date: 2026-07-11 15:34:28.537940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


revision: str = '9f1c8376a757'
down_revision: Union[str, None] = 'dc11add77d38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_repo', sa.Column('squash_on_merge', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_repo', 'squash_on_merge')
    # ### end Alembic commands ###
