"""dev run fault class (§request help)

Revision ID: a4c81f2e9b70
Revises: 685d59ada66e
Create Date: 2026-08-30 00:52:11.402118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


revision: str = 'a4c81f2e9b70'
down_revision: Union[str, None] = '685d59ada66e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dev_run', sa.Column('run_fault', sa.String(length=16), nullable=True))
    op.add_column('project', sa.Column('dev_run_fault', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'dev_run_fault')
    op.drop_column('dev_run', 'run_fault')
    # ### end Alembic commands ###
