"""message meta (§12 clarifying questions)

Revision ID: abd687a8409b
Revises: bc18484a9e81
Create Date: 2026-07-16 15:46:21.740022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


revision: str = 'abd687a8409b'
down_revision: Union[str, None] = 'bc18484a9e81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('meta', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'meta')
    # ### end Alembic commands ###
