"""project dev pod resource requests

Revision ID: ac63c881fc37
Revises: 639181b7e604
Create Date: 2026-08-13 08:24:21.682377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


revision: str = 'ac63c881fc37'
down_revision: Union[str, None] = '639181b7e604'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('dev_cpu_request', sa.String(length=16), nullable=True))
    op.add_column('project', sa.Column('dev_mem_request', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'dev_mem_request')
    op.drop_column('project', 'dev_cpu_request')
    # ### end Alembic commands ###
