"""model endpoint model_name + custom pricing; project config model_name nullable

Revision ID: bc18484a9e81
Revises: c98a16e6f770
Create Date: 2026-07-14 19:11:24.734502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


revision: str = 'bc18484a9e81'
down_revision: Union[str, None] = 'c98a16e6f770'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_endpoint', sa.Column('model_name', sa.String(length=128), nullable=True))
    op.add_column('model_endpoint', sa.Column('input_price', sa.Float(), nullable=True))
    op.add_column('model_endpoint', sa.Column('output_price', sa.Float(), nullable=True))
    op.alter_column('project_model_config', 'model_name',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project_model_config', 'model_name',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.drop_column('model_endpoint', 'output_price')
    op.drop_column('model_endpoint', 'input_price')
    op.drop_column('model_endpoint', 'model_name')
    # ### end Alembic commands ###
