"""model endpoints library + project endpoint_id

Revision ID: c98a16e6f770
Revises: 7c4d9f2a1e83
Create Date: 2026-07-14 17:50:06.704016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


revision: str = 'c98a16e6f770'
down_revision: Union[str, None] = '7c4d9f2a1e83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_endpoint',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('provider', sa.String(length=16), nullable=False),
    sa.Column('base_url', sa.String(length=512), nullable=False),
    sa.Column('api_key_enc', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('project_model_config', sa.Column('endpoint_id', sa.String(length=36), nullable=True))
    op.alter_column('project_model_config', 'openai_base_url',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
    op.alter_column('project_model_config', 'openai_api_key_enc',
               existing_type=sa.TEXT(),
               nullable=True)
    op.create_foreign_key('fk_project_model_config_endpoint_id', 'project_model_config',
                           'model_endpoint', ['endpoint_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_project_model_config_endpoint_id', 'project_model_config', type_='foreignkey')
    op.alter_column('project_model_config', 'openai_api_key_enc',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('project_model_config', 'openai_base_url',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
    op.drop_column('project_model_config', 'endpoint_id')
    op.drop_table('model_endpoint')
    # ### end Alembic commands ###
