"""user blocked

Revision ID: cef0e798a5e2
Revises: 929b25b5dc58
Create Date: 2026-08-15 20:51:23.688541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


revision: str = 'cef0e798a5e2'
down_revision: Union[str, None] = '929b25b5dc58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('blocked', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'blocked')
    # ### end Alembic commands ###
