"""request pr_urls (§PR chips)

Revision ID: cf88ae79f12b
Revises: b7e2c94d10af
Create Date: 2026-07-18 07:35:17.330188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


revision: str = 'cf88ae79f12b'
down_revision: Union[str, None] = 'b7e2c94d10af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('pr_urls', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request', 'pr_urls')
    # ### end Alembic commands ###
