"""global memory: org_memory + global_memory_enabled_default + project.use_global_memory

Revision ID: dc11add77d38
Revises: f1a2b3c4d5e6
Create Date: 2026-07-11 13:52:11.017070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


revision: str = 'dc11add77d38'
down_revision: Union[str, None] = 'f1a2b3c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('org_memory',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('author', sa.String(length=20), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value_enc', sa.Text(), nullable=False),
    sa.Column('is_secret', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'key')
    )
    op.create_index(op.f('ix_org_memory_org_id'), 'org_memory', ['org_id'], unique=False)
    op.add_column('organization', sa.Column('global_memory_enabled_default', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('project', sa.Column('use_global_memory', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'use_global_memory')
    op.drop_column('organization', 'global_memory_enabled_default')
    op.drop_index(op.f('ix_org_memory_org_id'), table_name='org_memory')
    op.drop_table('org_memory')
    # ### end Alembic commands ###
