"""initial

Revision ID: fd1e59138c16
Revises: 
Create Date: 2026-07-05 03:37:00.679360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


revision: str = 'fd1e59138c16'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_chunk',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('path', sa.String(length=512), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_chunk_source'), 'knowledge_chunk', ['source'], unique=False)
    op.create_table('organization',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('vat_id', sa.String(length=64), nullable=True),
    sa.Column('credit_balance', sa.Float(), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('speciality', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('block_auto_development', sa.Boolean(), nullable=False),
    sa.Column('from_scratch', sa.Boolean(), nullable=False),
    sa.Column('sovereign', sa.Boolean(), nullable=False),
    sa.Column('sovereign_comment', sa.Text(), nullable=True),
    sa.Column('gitlab_project_id', sa.Integer(), nullable=True),
    sa.Column('gitlab_ssh_url', sa.String(length=512), nullable=True),
    sa.Column('gitlab_web_url', sa.String(length=512), nullable=True),
    sa.Column('workspace_path', sa.String(length=512), nullable=True),
    sa.Column('ssh_public_key', sa.Text(), nullable=True),
    sa.Column('ssh_private_key_enc', sa.Text(), nullable=True),
    sa.Column('subdomain', sa.String(length=128), nullable=True),
    sa.Column('demo_basic_auth_user', sa.String(length=64), nullable=True),
    sa.Column('demo_basic_auth_pass_enc', sa.Text(), nullable=True),
    sa.Column('demo_port', sa.Integer(), nullable=True),
    sa.Column('demo_state', sa.String(length=16), nullable=False),
    sa.Column('demo_deployed_once', sa.Boolean(), nullable=False),
    sa.Column('demo_last_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('demo_last_stopped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tokens_consumed', sa.Integer(), nullable=False),
    sa.Column('cost_credits', sa.Float(), nullable=False),
    sa.Column('evaluation', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subdomain')
    )
    op.create_index(op.f('ix_project_org_id'), 'project', ['org_id'], unique=False)
    op.create_index(op.f('ix_project_status'), 'project', ['status'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('api_token',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_token_token_hash'), 'api_token', ['token_hash'], unique=True)
    op.create_index(op.f('ix_api_token_user_id'), 'api_token', ['user_id'], unique=False)
    op.create_table('credit_transaction',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('stripe_ref', sa.String(length=128), nullable=True),
    sa.Column('detail', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_transaction_org_id'), 'credit_transaction', ['org_id'], unique=False)
    op.create_table('deployment_event',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('detail', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deployment_event_project_id'), 'deployment_event', ['project_id'], unique=False)
    op.create_table('membership',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'user_id')
    )
    op.create_table('message',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('thread', sa.String(length=64), nullable=False),
    sa.Column('author', sa.String(length=20), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('emailed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_created_at'), 'message', ['created_at'], unique=False)
    op.create_index(op.f('ix_message_project_id'), 'message', ['project_id'], unique=False)
    op.create_table('onboarding_answer',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('question_id', sa.String(length=64), nullable=False),
    sa.Column('answer', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'question_id')
    )
    op.create_index(op.f('ix_onboarding_answer_project_id'), 'onboarding_answer', ['project_id'], unique=False)
    op.create_table('project_memory',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('author', sa.String(length=20), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value_enc', sa.Text(), nullable=False),
    sa.Column('is_secret', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'key')
    )
    op.create_index(op.f('ix_project_memory_project_id'), 'project_memory', ['project_id'], unique=False)
    op.create_table('project_model_config',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('openai_base_url', sa.String(length=512), nullable=False),
    sa.Column('openai_api_key_enc', sa.Text(), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_table('project_repo',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('ssh_uri', sa.String(length=512), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_repo_project_id'), 'project_repo', ['project_id'], unique=False)
    op.create_table('request',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('handling', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('price_credits', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_request_project_id'), 'request', ['project_id'], unique=False)
    op.create_table('status_change',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('from_status', sa.String(length=32), nullable=True),
    sa.Column('to_status', sa.String(length=32), nullable=False),
    sa.Column('actor', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=512), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_status_change_project_id'), 'status_change', ['project_id'], unique=False)
    op.create_table('quote',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('stripe_payment_link', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['request.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quote_project_id'), 'quote', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quote_project_id'), table_name='quote')
    op.drop_table('quote')
    op.drop_index(op.f('ix_status_change_project_id'), table_name='status_change')
    op.drop_table('status_change')
    op.drop_index(op.f('ix_request_project_id'), table_name='request')
    op.drop_table('request')
    op.drop_index(op.f('ix_project_repo_project_id'), table_name='project_repo')
    op.drop_table('project_repo')
    op.drop_table('project_model_config')
    op.drop_index(op.f('ix_project_memory_project_id'), table_name='project_memory')
    op.drop_table('project_memory')
    op.drop_index(op.f('ix_onboarding_answer_project_id'), table_name='onboarding_answer')
    op.drop_table('onboarding_answer')
    op.drop_index(op.f('ix_message_project_id'), table_name='message')
    op.drop_index(op.f('ix_message_created_at'), table_name='message')
    op.drop_table('message')
    op.drop_table('membership')
    op.drop_index(op.f('ix_deployment_event_project_id'), table_name='deployment_event')
    op.drop_table('deployment_event')
    op.drop_index(op.f('ix_credit_transaction_org_id'), table_name='credit_transaction')
    op.drop_table('credit_transaction')
    op.drop_index(op.f('ix_api_token_user_id'), table_name='api_token')
    op.drop_index(op.f('ix_api_token_token_hash'), table_name='api_token')
    op.drop_table('api_token')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_project_status'), table_name='project')
    op.drop_index(op.f('ix_project_org_id'), table_name='project')
    op.drop_table('project')
    op.drop_table('organization')
    op.drop_index(op.f('ix_knowledge_chunk_source'), table_name='knowledge_chunk')
    op.drop_table('knowledge_chunk')
    # ### end Alembic commands ###
