#!/usr/bin/env bash
# Manage git worktrees with per-worktree docker instances.
#
# Each worktree gets its own .env derived from the main checkout's .env, with a
# unique "instance slot" N following the multi-instance convention in CLAUDE.md
# (instance 2 = <project>2 / <domain>2.local / Traefik :8090 / postgres :5434 /
# SPA :5280 / landing :5281 / demos network <domain>2-demos). The main checkout
# keeps slot 1 (all compose defaults) and is never touched.
#
# Usage:
#   scripts/worktree.sh add <branch> [--slot N] [--from <ref>]
#   scripts/worktree.sh rm <branch-or-dir-name> [--purge]
#   scripts/worktree.sh list
set -euo pipefail

die() { echo "error: $*" >&2; exit 1; }

MAIN_WT=$(git worktree list --porcelain | head -1 | sed 's/^worktree //')
[ -n "$MAIN_WT" ] || die "not inside a git repository"
WT_PARENT="${MAIN_WT}-worktrees"

# Instance family: derived from the MAIN checkout's untracked .env so a branded
# fork's worktrees keep its identity (project family from COMPOSE_PROJECT_NAME,
# domain family from DEPLOY_DOMAIN minus .local). Neutral defaults otherwise.
FAM_PROJECT=$(grep -Es '^COMPOSE_PROJECT_NAME=' "$MAIN_WT/.env" 2>/dev/null | tail -1 | cut -d= -f2)
FAM_PROJECT="${FAM_PROJECT:-openvisor}"
FAM_DOMAIN=$(grep -Es '^DEPLOY_DOMAIN=' "$MAIN_WT/.env" 2>/dev/null | tail -1 | cut -d= -f2)
FAM_DOMAIN="${FAM_DOMAIN%.local}"
FAM_DOMAIN="${FAM_DOMAIN:-openvisor}"

slot_vars() { # $1 = slot number -> echoes KEY=VALUE lines
  local n=$1
  local http=$((8070 + 10 * n))
  echo "INSTANCE_SLOT=${n}"
  echo "COMPOSE_PROJECT_NAME=${FAM_PROJECT}${n}"
  echo "DEPLOY_DOMAIN=${FAM_DOMAIN}${n}.local"
  echo "DEMOS_NETWORK=${FAM_DOMAIN}${n}-demos"
  echo "TRAEFIK_HTTP_PORT=${http}"
  echo "TRAEFIK_DASHBOARD_PORT=$((http + 1))"
  echo "POSTGRES_DEV_PORT=$((5432 + n))"
  echo "APP_DEV_PORT=$((5080 + 100 * n))"
  echo "LANDING_DEV_PORT=$((5081 + 100 * n))"
  echo "APP_BASE_URL=http://app.${FAM_DOMAIN}${n}.local:${http}"
  echo "LANDING_BASE_URL=http://${FAM_DOMAIN}${n}.local:${http}"
}

used_slots() { # slots taken by existing worktree .envs
  [ -d "$WT_PARENT" ] || return 0
  grep -hs '^INSTANCE_SLOT=' "$WT_PARENT"/*/.env 2>/dev/null | cut -d= -f2
}

next_free_slot() {
  local n=2 taken
  taken=$(used_slots)
  while echo "$taken" | grep -qx "$n"; do n=$((n + 1)); done
  echo "$n"
}

write_env() { # $1 = worktree path, $2 = slot
  local wt=$1 slot=$2 overridden keys
  keys="INSTANCE_SLOT|COMPOSE_PROJECT_NAME|DEPLOY_DOMAIN|DEMOS_NETWORK|TRAEFIK_HTTP_PORT|TRAEFIK_DASHBOARD_PORT|POSTGRES_DEV_PORT|APP_DEV_PORT|LANDING_DEV_PORT|APP_BASE_URL|LANDING_BASE_URL"
  # Copy the main .env, commenting out any key the instance block overrides.
  awk -v keys="$keys" '
    $0 ~ "^(" keys ")=" { print "# [worktree override] " $0; next }
    { print }
  ' "$MAIN_WT/.env" > "$wt/.env"
  {
    echo ""
    echo "# --- worktree instance identity (slot ${slot}) - generated by scripts/worktree.sh ---"
    slot_vars "$slot"
  } >> "$wt/.env"
}

hosts_hint() { # $1 = slot
  local n=$1 missing="" h
  for h in "${FAM_DOMAIN}${n}.local" "app.${FAM_DOMAIN}${n}.local" "mail.${FAM_DOMAIN}${n}.local"; do
    grep -qE "[[:space:]]${h}([[:space:]]|\$)" /etc/hosts || missing="$missing $h"
  done
  if [ -n "$missing" ]; then
    echo "Missing /etc/hosts entries. Add them with:"
    echo "  echo '127.0.0.1${missing}' | sudo tee -a /etc/hosts"
  fi
}

cmd_add() {
  local branch="" slot="" from="main" arg
  while [ $# -gt 0 ]; do
    case $1 in
      --slot) slot=$2; shift 2 ;;
      --from) from=$2; shift 2 ;;
      -*) die "unknown flag: $1" ;;
      *) [ -z "$branch" ] || die "unexpected argument: $1"; branch=$1; shift ;;
    esac
  done
  [ -n "$branch" ] || die "usage: worktree.sh add <branch> [--slot N] [--from <ref>]"
  [ -f "$MAIN_WT/.env" ] || die "no .env in main checkout ($MAIN_WT) to derive from"
  [ -n "$slot" ] || slot=$(next_free_slot)
  echo "$slot" | grep -qE '^([2-9]|[1-9][0-9]+)$' || die "slot must be an integer >= 2 (1 is the main checkout)"
  if used_slots | grep -qx "$slot"; then die "slot $slot is already used by another worktree"; fi

  local slug wt
  slug=$(echo "$branch" | tr '/' '-')
  wt="$WT_PARENT/$slug"
  [ ! -e "$wt" ] || die "$wt already exists"
  mkdir -p "$WT_PARENT"

  if git -C "$MAIN_WT" show-ref --verify --quiet "refs/heads/$branch"; then
    git -C "$MAIN_WT" worktree add "$wt" "$branch"
  elif git -C "$MAIN_WT" show-ref --verify --quiet "refs/remotes/origin/$branch"; then
    git -C "$MAIN_WT" worktree add --track -b "$branch" "$wt" "origin/$branch"
  else
    git -C "$MAIN_WT" worktree add -b "$branch" "$wt" "$from"
    echo "Created new branch '$branch' from '$from'."
  fi

  write_env "$wt" "$slot"
  echo "Wrote $wt/.env (instance slot $slot)."

  # Gitignored/untracked files a worktree also needs, when present upstream.
  if [ -f "$MAIN_WT/.claude/settings.json" ] && [ ! -f "$wt/.claude/settings.json" ]; then
    mkdir -p "$wt/.claude" && cp "$MAIN_WT/.claude/settings.json" "$wt/.claude/settings.json"
  fi
  if ls "$MAIN_WT"/traefik/certs/*.pem >/dev/null 2>&1; then
    mkdir -p "$wt/traefik/certs" && cp "$MAIN_WT"/traefik/certs/*.pem "$wt/traefik/certs/"
  fi
  # Local knowledge base (gitignored ./knowledge folder, machine-local like .env):
  # copy it in when present so the worktree's KB ingestion has the same corpus.
  if [ -d "$MAIN_WT/knowledge" ] && [ ! -e "$wt/knowledge" ]; then
    cp -a "$MAIN_WT/knowledge" "$wt/knowledge"
  else
    echo "note: no ./knowledge folder to copy (ok for dev; KB ingestion will see an empty /knowledge)."
  fi

  echo ""
  hosts_hint "$slot"
  echo ""
  echo "Worktree ready: $wt"
  echo "  cd $wt && make dev    # app at http://app.${FAM_DOMAIN}${slot}.local:$((8070 + 10 * slot)), mail at http://mail.${FAM_DOMAIN}${slot}.local:$((8070 + 10 * slot))"
}

# Give the invoking user back the files a container created as root inside `dir`.
# Only a root process can do it, so it runs in a throwaway container on the same
# mount - the same reason the files exist in the first place.
reclaim_root_owned() {
  local dir=$1 stray
  # A recursive chown deserves a guard of its own: only ever inside WT_PARENT.
  case "$dir" in
    "$WT_PARENT"/?*) ;;
    *) die "refusing to reclaim outside $WT_PARENT: $dir" ;;
  esac
  # No pipe to grep here: the teardown above documents how a short-circuiting
  # reader can SIGPIPE its producer, and that would read as "nothing to do".
  stray=$(find "$dir" ! -user "$(id -u)" -print -quit 2>/dev/null || true)
  [ -n "$stray" ] || return 0
  echo "note: reclaiming container-created files in $dir"
  docker run --rm -v "$dir:/wt" alpine:3 chown -R "$(id -u):$(id -g)" /wt \
    || echo "warning: could not reclaim container-created files; removal may fail"
}

cmd_rm() {
  local name="" purge=0
  while [ $# -gt 0 ]; do
    case $1 in
      --purge) purge=1; shift ;;
      -*) die "unknown flag: $1" ;;
      *) [ -z "$name" ] || die "unexpected argument: $1"; name=$1; shift ;;
    esac
  done
  [ -n "$name" ] || die "usage: worktree.sh rm <branch-or-dir-name> [--purge]"
  local wt="$WT_PARENT/$(echo "$name" | tr '/' '-')"
  [ -d "$wt" ] || die "no worktree at $wt"

  # Tear down this worktree's docker stack before the compose files disappear.
  # Not `ps -q | grep -q .`: under pipefail, grep -q closing the pipe early can
  # kill compose with SIGPIPE (141) and silently skip teardown - and a docker
  # error must abort, not read as "nothing running" (a skipped teardown leaves
  # the stack orphaned and its bind mounts block the worktree removal below).
  local project running
  project=$(grep -s '^COMPOSE_PROJECT_NAME=' "$wt/.env" | cut -d= -f2 || true)
  if [ -n "$project" ]; then
    running=$(docker compose -p "$project" ps -q 2>/dev/null) \
      || die "could not check for running containers of '$project' (is docker up?); aborting before touching $wt"
    if [ -n "$running" ]; then
      if [ "$purge" = 1 ]; then
        docker compose -p "$project" down --volumes --remove-orphans
      else
        docker compose -p "$project" down --remove-orphans
        echo "note: named volumes of '$project' were kept; re-run with --purge to delete them."
      fi
    fi
  else
    echo "warning: no COMPOSE_PROJECT_NAME in $wt/.env; skipping docker teardown (stop any leftover stack with: docker compose -p <project> down)."
  fi

  # Containers write into the worktree through bind mounts AS ROOT (node_modules,
  # __pycache__, landing/.astro, the materialized static_data json), and those files
  # are not ours to unlink - which is what makes the removal below fail with
  # "Permission denied" and strand the directory. Hand them back first, after the
  # teardown above so nothing is still writing.
  reclaim_root_owned "$wt"

  # Clear the files this script generated (they read as "dirty" to git); real
  # uncommitted work still blocks removal below.
  local f
  for f in .env .claude/settings.json; do
    if [ -f "$wt/$f" ] && ! git -C "$wt" ls-files --error-unmatch "$f" >/dev/null 2>&1; then
      rm -f "$wt/$f"
    fi
  done
  rm -f "$wt"/traefik/certs/*.pem 2>/dev/null || true
  rm -rf "$wt/knowledge" 2>/dev/null || true  # gitignored local KB copy

  local leftover
  leftover=$(git -C "$wt" status --porcelain)
  [ -z "$leftover" ] || die "worktree has uncommitted work; commit/stash it there first:
$leftover"
  # --force: we just verified the tracked tree is clean; force past any residual
  # gitignored/untracked state git would otherwise refuse to remove.
  git -C "$MAIN_WT" worktree remove --force "$wt"
  echo "Removed $wt (branch kept; delete it with: git branch -d <branch>)."
}

cmd_list() {
  git -C "$MAIN_WT" worktree list
  [ -d "$WT_PARENT" ] || return 0
  local env
  for env in "$WT_PARENT"/*/.env; do
    [ -f "$env" ] || continue
    echo "$(dirname "$env"): slot $(grep -s '^INSTANCE_SLOT=' "$env" | cut -d= -f2), $(grep -s '^APP_BASE_URL=' "$env" | cut -d= -f2-)"
  done
}

case "${1:-}" in
  add) shift; cmd_add "$@" ;;
  rm) shift; cmd_rm "$@" ;;
  list) shift; cmd_list "$@" ;;
  *) sed -n '2,13p' "$0" | sed 's/^# \{0,1\}//'; exit 1 ;;
esac
